# Generated by Django 5.0.10 on 2025-10-08 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0006_campaign_is_active_alter_campaign_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
