# Generated by Django 5.0.10 on 2025-10-08 05:28

from django.db import migrations, connection


def remove_created_at_if_exists(apps, schema_editor):
    """Remove created_at column if it exists"""
    with connection.cursor() as cursor:
        # Check database type
        db_type = connection.vendor
        
        if db_type == 'sqlite':
            # SQLite syntax
            cursor.execute("""
                SELECT COUNT(*) FROM pragma_table_info('campaign_donation') 
                WHERE name = 'created_at'
            """)
            column_exists = cursor.fetchone()[0] > 0
            
            if column_exists:
                cursor.execute("ALTER TABLE campaign_donation DROP COLUMN created_at")
                
        elif db_type == 'postgresql':
            # PostgreSQL syntax
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.columns 
                WHERE table_name = 'campaign_donation' AND column_name = 'created_at'
            """)
            column_exists = cursor.fetchone()[0] > 0
            
            if column_exists:
                cursor.execute("ALTER TABLE campaign_donation DROP COLUMN created_at")


def reverse_remove_created_at(apps, schema_editor):
    """Reverse migration - no need to do anything"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0006_campaign_is_active_alter_campaign_status"),
    ]

    operations = [
        migrations.RunPython(remove_created_at_if_exists, reverse_remove_created_at),
    ]
